//! Setup script generator for `samo_ops` wrapper functions.
//!
//! Generates SQL to create the `samo_ops` schema, `samo_agent` role,
//! and SECURITY DEFINER wrapper functions for operations that require
//! elevated privileges.
//!
//! On PG 16+, recommends `pg_maintain` role instead of wrappers for
//! maintenance operations (VACUUM, REINDEX CONCURRENTLY).

use std::fmt::Write as _;

/// Generate the complete setup SQL for `samo_ops` wrappers.
///
/// When `pg_version >= 16`, maintenance operations (vacuum, reindex)
/// use `pg_maintain` instead of SECURITY DEFINER wrappers.
pub fn generate_setup_sql(pg_version: u32) -> String {
    let mut sql = String::new();

    header(&mut sql);
    create_schema_and_role(&mut sql);
    cancel_terminate_wrappers(&mut sql);
    guc_wrappers(&mut sql);

    if pg_version >= 16 {
        pg_maintain_grants(&mut sql);
    } else {
        maintenance_wrappers(&mut sql);
    }

    revoke_public(&mut sql);
    footer(&mut sql, pg_version);

    sql
}

fn header(sql: &mut String) {
    sql.push_str("-- ==========================================================================\n");
    sql.push_str("-- Samo setup: samo_ops wrapper functions\n");
    sql.push_str("-- Generated by: samo --generate-wrappers\n");
    sql.push_str("--\n");
    sql.push_str("-- Review this script carefully before executing.\n");
    sql.push_str("-- Execute as a superuser or a role with CREATEROLE privilege.\n");
    sql.push_str(
        "-- ==========================================================================\n\n",
    );
    sql.push_str("BEGIN;\n\n");
}

fn create_schema_and_role(sql: &mut String) {
    sql.push_str(
        "-- Create the samo_agent role (nologin — connect with a user GRANTed this role)\n",
    );
    sql.push_str("DO $$\nBEGIN\n");
    sql.push_str("  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'samo_agent') THEN\n");
    sql.push_str("    CREATE ROLE samo_agent NOLOGIN;\n");
    sql.push_str("  END IF;\n");
    sql.push_str("END\n$$;\n\n");

    sql.push_str("-- Create the samo_ops schema for wrapper functions\n");
    sql.push_str("CREATE SCHEMA IF NOT EXISTS samo_ops;\n");
    sql.push_str("GRANT USAGE ON SCHEMA samo_ops TO samo_agent;\n\n");
}

fn cancel_terminate_wrappers(sql: &mut String) {
    sql.push_str(
        "-- ---------------------------------------------------------------------------\n",
    );
    sql.push_str("-- Cancel / terminate wrappers\n");
    sql.push_str(
        "-- ---------------------------------------------------------------------------\n\n",
    );

    // cancel_query
    sql.push_str(
        "\
CREATE OR REPLACE FUNCTION samo_ops.cancel_query(p_pid integer)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, pg_temp
AS $$
BEGIN
  -- Validate: target must be a client backend, not ourselves
  IF p_pid = pg_backend_pid() THEN
    RAISE EXCEPTION 'Cannot cancel own backend';
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_stat_activity
    WHERE pid = p_pid AND backend_type = 'client backend'
  ) THEN
    RAISE EXCEPTION 'PID % is not a client backend', p_pid;
  END IF;
  RETURN pg_cancel_backend(p_pid);
END;
$$;

GRANT EXECUTE ON FUNCTION samo_ops.cancel_query(integer) TO samo_agent;

",
    );

    // terminate_backend
    sql.push_str(
        "\
CREATE OR REPLACE FUNCTION samo_ops.terminate_backend(p_pid integer)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, pg_temp
AS $$
BEGIN
  IF p_pid = pg_backend_pid() THEN
    RAISE EXCEPTION 'Cannot terminate own backend';
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_stat_activity
    WHERE pid = p_pid AND backend_type = 'client backend'
  ) THEN
    RAISE EXCEPTION 'PID % is not a client backend', p_pid;
  END IF;
  RETURN pg_terminate_backend(p_pid);
END;
$$;

GRANT EXECUTE ON FUNCTION samo_ops.terminate_backend(integer) TO samo_agent;

",
    );
}

fn guc_wrappers(sql: &mut String) {
    sql.push_str(
        "-- ---------------------------------------------------------------------------\n",
    );
    sql.push_str("-- GUC change wrappers (safe parameters only)\n");
    sql.push_str(
        "-- ---------------------------------------------------------------------------\n\n",
    );

    sql.push_str(
        "\
CREATE OR REPLACE FUNCTION samo_ops.set_guc(p_name text, p_value text)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, pg_temp
AS $$
DECLARE
  v_safe_gucs text[] := ARRAY[
    'idle_in_transaction_session_timeout',
    'lock_timeout',
    'statement_timeout',
    'log_min_duration_statement',
    'deadlock_timeout',
    'work_mem',
    'maintenance_work_mem',
    'temp_buffers',
    'effective_cache_size'
  ];
BEGIN
  IF NOT (p_name = ANY(v_safe_gucs)) THEN
    RAISE EXCEPTION 'GUC \"%\" is not in the safe list', p_name;
  END IF;
  -- Validate the parameter exists and value is accepted
  PERFORM set_config(p_name, p_value, false);
END;
$$;

GRANT EXECUTE ON FUNCTION samo_ops.set_guc(text, text) TO samo_agent;

",
    );

    sql.push_str(
        "\
CREATE OR REPLACE FUNCTION samo_ops.alter_system_guc(p_name text, p_value text)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, pg_temp
AS $$
DECLARE
  v_safe_gucs text[] := ARRAY[
    'idle_in_transaction_session_timeout',
    'lock_timeout',
    'statement_timeout',
    'log_min_duration_statement',
    'deadlock_timeout',
    'work_mem',
    'maintenance_work_mem',
    'temp_buffers',
    'effective_cache_size'
  ];
BEGIN
  IF NOT (p_name = ANY(v_safe_gucs)) THEN
    RAISE EXCEPTION 'GUC \"%\" is not in the safe list', p_name;
  END IF;
  EXECUTE format('ALTER SYSTEM SET %I = %L', p_name, p_value);
END;
$$;

GRANT EXECUTE ON FUNCTION samo_ops.alter_system_guc(text, text) TO samo_agent;

",
    );

    sql.push_str(
        "\
CREATE OR REPLACE FUNCTION samo_ops.reset_system_guc(p_name text)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, pg_temp
AS $$
DECLARE
  v_safe_gucs text[] := ARRAY[
    'idle_in_transaction_session_timeout',
    'lock_timeout',
    'statement_timeout',
    'log_min_duration_statement',
    'deadlock_timeout',
    'work_mem',
    'maintenance_work_mem',
    'temp_buffers',
    'effective_cache_size'
  ];
BEGIN
  IF NOT (p_name = ANY(v_safe_gucs)) THEN
    RAISE EXCEPTION 'GUC \"%\" is not in the safe list', p_name;
  END IF;
  EXECUTE format('ALTER SYSTEM RESET %I', p_name);
END;
$$;

GRANT EXECUTE ON FUNCTION samo_ops.reset_system_guc(text) TO samo_agent;

",
    );
}

fn maintenance_wrappers(sql: &mut String) {
    sql.push_str(
        "-- ---------------------------------------------------------------------------\n",
    );
    sql.push_str("-- Maintenance wrappers (PG 14-15 only — on PG 16+, use pg_maintain)\n");
    sql.push_str(
        "-- ---------------------------------------------------------------------------\n\n",
    );

    sql.push_str(
        "\
CREATE OR REPLACE FUNCTION samo_ops.reindex_concurrently(p_index regclass)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, pg_temp
AS $$
BEGIN
  -- Validate: target must actually be an index
  IF NOT EXISTS (
    SELECT 1 FROM pg_class WHERE oid = p_index AND relkind = 'i'
  ) THEN
    RAISE EXCEPTION '% is not an index', p_index;
  END IF;
  EXECUTE format('REINDEX INDEX CONCURRENTLY %I.%I',
    (SELECT nspname FROM pg_namespace WHERE oid = (
      SELECT relnamespace FROM pg_class WHERE oid = p_index)),
    (SELECT relname FROM pg_class WHERE oid = p_index));
END;
$$;

GRANT EXECUTE ON FUNCTION samo_ops.reindex_concurrently(regclass) TO samo_agent;

",
    );

    sql.push_str(
        "\
CREATE OR REPLACE FUNCTION samo_ops.vacuum_table(p_table regclass)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, pg_temp
AS $$
BEGIN
  -- Validate: target must be a regular table or partitioned table
  IF NOT EXISTS (
    SELECT 1 FROM pg_class WHERE oid = p_table AND relkind IN ('r', 'p')
  ) THEN
    RAISE EXCEPTION '% is not a table', p_table;
  END IF;
  EXECUTE format('VACUUM ANALYZE %I.%I',
    (SELECT nspname FROM pg_namespace WHERE oid = (
      SELECT relnamespace FROM pg_class WHERE oid = p_table)),
    (SELECT relname FROM pg_class WHERE oid = p_table));
END;
$$;

GRANT EXECUTE ON FUNCTION samo_ops.vacuum_table(regclass) TO samo_agent;

",
    );
}

fn pg_maintain_grants(sql: &mut String) {
    sql.push_str(
        "-- ---------------------------------------------------------------------------\n",
    );
    sql.push_str("-- PG 16+: use pg_maintain instead of wrapper functions for maintenance\n");
    sql.push_str(
        "-- ---------------------------------------------------------------------------\n\n",
    );
    sql.push_str("GRANT pg_maintain TO samo_agent;\n");
    sql.push_str("-- samo_agent can now directly execute VACUUM, REINDEX CONCURRENTLY, etc.\n");
    sql.push_str("-- without SUPERUSER and without wrapper functions.\n\n");
}

fn revoke_public(sql: &mut String) {
    sql.push_str(
        "-- ---------------------------------------------------------------------------\n",
    );
    sql.push_str("-- Revoke from PUBLIC (defense in depth)\n");
    sql.push_str(
        "-- ---------------------------------------------------------------------------\n\n",
    );
    sql.push_str("REVOKE ALL ON ALL FUNCTIONS IN SCHEMA samo_ops FROM PUBLIC;\n\n");
}

fn footer(sql: &mut String, pg_version: u32) {
    sql.push_str("COMMIT;\n\n");
    sql.push_str("-- ==========================================================================\n");
    let _ = writeln!(sql, "-- Setup complete (targeting PG {pg_version}+).");
    sql.push_str("--\n");
    sql.push_str("-- Next steps:\n");
    sql.push_str("--   1. Review the SQL above\n");
    sql.push_str("--   2. Execute as superuser\n");
    sql.push_str("--   3. GRANT samo_agent TO your_connection_user;\n");
    sql.push_str("--   4. Connect with --autonomy=supervised or --autonomy=auto\n");
    sql.push_str("-- ==========================================================================\n");
}

// ---------------------------------------------------------------------------
// Unit tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn setup_sql_contains_schema_creation() {
        let sql = generate_setup_sql(16);
        assert!(sql.contains("CREATE SCHEMA IF NOT EXISTS samo_ops"));
        assert!(sql.contains("samo_agent"));
    }

    #[test]
    fn setup_sql_contains_cancel_terminate() {
        let sql = generate_setup_sql(14);
        assert!(sql.contains("samo_ops.cancel_query"));
        assert!(sql.contains("samo_ops.terminate_backend"));
        assert!(sql.contains("pg_cancel_backend"));
        assert!(sql.contains("pg_terminate_backend"));
    }

    #[test]
    fn setup_sql_contains_guc_wrappers() {
        let sql = generate_setup_sql(14);
        assert!(sql.contains("samo_ops.set_guc"));
        assert!(sql.contains("samo_ops.alter_system_guc"));
        assert!(sql.contains("samo_ops.reset_system_guc"));
        assert!(sql.contains("idle_in_transaction_session_timeout"));
    }

    #[test]
    fn pg14_includes_maintenance_wrappers() {
        let sql = generate_setup_sql(14);
        assert!(sql.contains("samo_ops.reindex_concurrently"));
        assert!(sql.contains("samo_ops.vacuum_table"));
        assert!(!sql.contains("GRANT pg_maintain"));
    }

    #[test]
    fn pg16_uses_pg_maintain() {
        let sql = generate_setup_sql(16);
        assert!(sql.contains("GRANT pg_maintain TO samo_agent"));
        assert!(!sql.contains("CREATE OR REPLACE FUNCTION samo_ops.reindex_concurrently"));
        assert!(!sql.contains("CREATE OR REPLACE FUNCTION samo_ops.vacuum_table"));
    }

    #[test]
    fn setup_sql_has_security_definer() {
        let sql = generate_setup_sql(14);
        assert!(sql.contains("SECURITY DEFINER"));
        assert!(sql.contains("SET search_path = pg_catalog, pg_temp"));
    }

    #[test]
    fn setup_sql_revokes_public() {
        let sql = generate_setup_sql(16);
        assert!(sql.contains("REVOKE ALL ON ALL FUNCTIONS IN SCHEMA samo_ops FROM PUBLIC"));
    }

    #[test]
    fn setup_sql_wrapped_in_transaction() {
        let sql = generate_setup_sql(16);
        assert!(sql.starts_with("-- =="));
        assert!(sql.contains("BEGIN;"));
        assert!(sql.contains("COMMIT;"));
    }

    #[test]
    fn self_cancel_protection() {
        let sql = generate_setup_sql(14);
        assert!(sql.contains("Cannot cancel own backend"));
        assert!(sql.contains("Cannot terminate own backend"));
    }

    #[test]
    fn guc_whitelist_validation() {
        let sql = generate_setup_sql(14);
        // All three GUC wrapper functions check the safe list
        let occurrences = sql.matches("v_safe_gucs").count();
        assert!(occurrences >= 3, "Expected at least 3 safe GUC list checks");
    }
}
